disabled_rules:
  - trailing_comma
  - opening_brace
  - todo
  - redundant_string_enum_value
  - type_body_length
  - file_length
  - closure_parameter_position
  - multiple_closures_with_trailing_closure
  - large_tuple
  - identifier_name
  - type_name
  - function_body_length
  - line_length
  - function_parameter_count
  - statement_position
excluded:
  - Modules/Firebase
  - vendored
  - fastlane
  - Carthage
  - vendor
  - scripts
  - Danger
  - mapbox-navigation-ios

nesting:
  type_level: 2

custom_rules:
  dont_use_print:
    included: ".*\\.swift"
    name: "Don't use `print`"
    regex: "(^|[^\\w])(print)\\("
    match_kinds:
      - identifier
    capture_group: 2
    message: "Use Log[<category>] from Common shared library (not MapboxCommon) instead of `print`s."
    severity: warning
